services:
  # Backend + Frontend (serveur Node.js qui sert aussi les fichiers statiques)
  - type: web
    name: promptr
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SOLANA_NETWORK
        value: mainnet-beta
      - key: SOLANA_RPC_URL
        sync: false
      - key: X402_AMOUNT_USDC
        value: 0.001
      - key: X402_RECEIVER_ADDRESS
        value: 3LrVwGYoqUgvwUadaCrkpqBNqkgVcWpac7CYM99KbQHk
      - key: X402_FACILITATOR_API_URL
        value: https://facilitator.payai.network
      - key: LOG_LEVEL
        value: info
      - key: LOG_FILE
        value: logs/app.log
      - key: VITE_DONATION_ADDRESS
        value: 3LrVwGYoqUgvwUadaCrkpqBNqkgVcWpac7CYM99KbQHk
